# Site settings
title: ToCraft
email: development@tocraft.dev
description: I'm a software developer and also very interested in Minecraft Modding.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tocraft.dev" # the base hostname & protocol for your site
author: ToCraft
street_address:
city:
state:
zip_code:
country: Germany
phone:

# Social settings
facebook_url:
github_url: https://github.com/ToCraft
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/to_craft.dev
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
style: compressed